name: reacount_2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  focused_menu: ^1.0.5
  get: ^4.3.8
  get_it: ^7.2.0
  jiffy: ^4.1.0
  mockito: ^5.0.16
  path_provider: ^2.0.0
  sentry_flutter: ^6.0.1
  sqflite: ^2.0.0+4

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

